import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { DraftChapterBundleSchema, PublishableChapterBundleSchema, ExternalEmbedSchema, OperationEnvelopeSchema, ContentSourceDescriptorSchema, jsonSchemas } from "../../packages/content-contract/src/index.ts";

const hash = "a".repeat(64); const actor = { actorId: "actor_joel", actorType: "human" as const };
const base = { schemaVersion: 2 as const, chapterId: "chapter_01", contentKey: "ch01", slug: "a-chapter", title: "A Chapter", description: "A description", part: { partId: "part_01", title: "Part I", order: 1 }, order: 1, chapterVersion: "1.0", revisionId: "revision_01", body: [{ type: "heading" as const, blockId: "block_heading", sectionId: "section_01", level: 2, text: "Start" }, { type: "paragraph" as const, blockId: "block_paragraph", passageId: "passage_01", text: "Argument." }], reasoningObjective: "Evaluate an argument.", readingRecordLicense: "CC0-1.0" as const, sidePanelModules: [{ moduleId: "module_reading", type: "readingRecord" as const, order: 0 }], annotations: [], sources: [], people: [], concepts: [], traditions: [], worldLayer: { worldLayerId: "world_01", version: "1" }, diagrams: [], mediaPlacementIds: [], rightsCaseIds: [], licenses: { chapter: "CC-BY-4.0", assets: [] }, exports: { web: true, print: true, offline: true, voice: true }, aliases: [], tombstones: [], updatedBy: actor, updatedAt: "2026-08-02T12:00:00.000Z" };
const checkpoint = (slot: "commit" | "work" | "reconcile", n: string) => ({ checkpointId: `checkpoint_${n}`, passageId: "passage_01", passageExcerptHash: hash, slot, stage: slot, strategy: "initial-judgment" as const, title: slot, trigger: "Pause.", prompt: "Respond.", guidance: "Be concrete.", responseStructure: "prose" as const, minWords: 30, maxWords: 250, showInSidebar: true, rationale: "Practice judgment." });

test("draft accepts zero to three unique fixed slots", () => { assert.equal(DraftChapterBundleSchema.safeParse({ ...base, status: "draft", checkpoints: [] }).success, true); assert.equal(DraftChapterBundleSchema.safeParse({ ...base, status: "draft", checkpoints: [checkpoint("commit", "1"), checkpoint("commit", "2")] }).success, false); });
test("publication requires Commit, Work, Reconcile in order", () => { assert.equal(PublishableChapterBundleSchema.safeParse({ ...base, status: "approved", checkpoints: [checkpoint("commit", "1"), checkpoint("work", "2"), checkpoint("reconcile", "3")] }).success, true); assert.equal(PublishableChapterBundleSchema.safeParse({ ...base, status: "approved", checkpoints: [checkpoint("work", "1"), checkpoint("commit", "2"), checkpoint("reconcile", "3")] }).success, false); });
test("checkpoint side-panel and word-bound controls are validated", () => { assert.equal(DraftChapterBundleSchema.safeParse({ ...base, status: "draft", checkpoints: [{ ...checkpoint("commit", "1"), minWords: 300, maxWords: 250 }] }).success, false); assert.equal(DraftChapterBundleSchema.safeParse({ ...base, status: "draft", checkpoints: [{ ...checkpoint("commit", "1"), showInSidebar: false }] }).success, true); });
test("external embeds are typed and cannot carry raw markup", () => { const good = { type: "externalEmbed" as const, blockId: "block_embed", embedId: "embed_01", identity: { provider: "youtube" as const, resourceType: "video" as const, resourceId: "abc" }, canonicalUrl: "https://www.youtube.com/watch?v=abc", caption: "Video", teachingUse: "Compare arguments.", displayPreset: "reading" as const, theme: "auto" as const, options: { provider: "youtube" as const, captions: true }, fallback: { title: "Video", summary: "Summary", linkLabel: "Open", accessedAt: "2026-08-02T12:00:00.000Z" }, adapterVersion: "1" }; assert.equal(ExternalEmbedSchema.safeParse(good).success, true); assert.equal(ExternalEmbedSchema.safeParse({ ...good, options: { provider: "x", conversation: true } }).success, false); assert.equal(ExternalEmbedSchema.safeParse({ ...good, embedHtml: "<iframe>" }).success, false); });
test("extended providers remain typed and fallback-first", () => {
  const common = { type: "externalEmbed" as const, blockId: "block_embed", embedId: "embed_01", caption: "Media", teachingUse: "Compare the account.", displayPreset: "reading" as const, theme: "auto" as const, fallback: { title: "Media", summary: "Authored summary", linkLabel: "Open", accessedAt: "2026-08-02T12:00:00.000Z" }, adapterVersion: "1" };
  assert.equal(ExternalEmbedSchema.safeParse({ ...common, identity: { provider: "spotify", resourceType: "track", resourceId: "4uLU6hMCjMI75M1A2tKUQC" }, canonicalUrl: "https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC", options: { provider: "spotify", explicitConsent: true } }).success, true);
  assert.equal(ExternalEmbedSchema.safeParse({ ...common, identity: { provider: "soundcloud", resourceType: "track", resourceId: "artist:track" }, canonicalUrl: "https://soundcloud.com/artist/track", options: { provider: "soundcloud", linkFirst: true } }).success, true);
  assert.equal(ExternalEmbedSchema.safeParse({ ...common, identity: { provider: "bluesky", resourceType: "post", resourceId: "abc123" }, canonicalUrl: "https://bsky.app/profile/example.bsky.social/post/abc123", options: { provider: "bluesky", linkFirst: true } }).success, true);
});
test("semantic envelopes bind operation ID, CAS revision, and idempotency", () => { const e = { operationId: "op_01", idempotencyKey: "a0d4b181-854e-4754-9ec3-5f9bc1da0933", changeSetId: "changeset_01", expectedBaseRevisionId: "revision_01", actor, submittedAt: "2026-08-02T12:00:00.000Z", operation: { kind: "replaceText" as const, operationId: "op_01", blockId: "block_paragraph", text: "Revised." } }; assert.equal(OperationEnvelopeSchema.safeParse(e).success, true); assert.equal(OperationEnvelopeSchema.safeParse({ ...e, operation: { ...e.operation, operationId: "op_no" } }).success, false); });
test("JSON schema is derived from release and command contracts", () => { assert.ok("definitions" in jsonSchemas.bookReleaseSnapshot); assert.ok("definitions" in jsonSchemas.operationEnvelope); });
test("content authority is explicitly Git or D1, never a vendor-specific direct-write path", () => {
  assert.equal(ContentSourceDescriptorSchema.safeParse({ authority: "d1", documentId: "chapter_01", domainRevisionId: "revision_01", normalizedSnapshotHash: hash }).success, true);
  assert.equal(ContentSourceDescriptorSchema.safeParse({ authority: "sanity", projectId: "project", dataset: "production", domainRevisionId: "revision_01", normalizedSnapshotHash: hash }).success, false);
});
test("frozen OpenAPI is valid JSON and exposes the complete agent and human boundary", () => {
  const spec = JSON.parse(readFileSync(new URL("../../packages/content-contract/openapi/content-api.v1.openapi.json", import.meta.url), "utf8"));
  assert.equal(spec.openapi, "3.1.0");
  assert.equal(Object.keys(spec.paths).length >= 29, true);
  assert.equal(spec.paths["/v1/media-review-packages"].post["x-agent-safe"], true);
  assert.equal(spec.paths["/v1/media-review-packages/{reviewPackageId}:decide"].post["x-human-only"], true);
  assert.equal(spec.paths["/v1/changesets/{changesetId}:approve"].post["x-human-only"], true);
  assert.equal(spec.paths["/v1/changesets/{changesetId}:publish"].post["x-human-only"], true);
  assert.equal(spec.paths["/v1/changesets/{changesetId}:publish"].post["x-enabled"], false);
  assert.deepEqual(spec.paths["/v1/changesets/{changesetId}:renderPreview"].post["x-preview-properties"], { immutableSnapshot: true, oneTime: true, ttlSeconds: 300, authoringCredentials: false });
  assert.deepEqual(spec.components.requestBodies.mutationEnvelope.content["application/json"].schema.properties.operation.properties.type.enum, ["text.replace", "block.insert", "block.move", "checkpoint.upsert", "checkpoint.replace", "checkpoint.remove", "embed.upsert", "media.place", "media.remove"]);
  assert.equal(spec.paths["/v1/release-assets/{sha256}"].get["x-exact-sha256-bytes"], true);
  assert.deepEqual(spec["x-rate-limits"], { persistence: "D1 fail-closed fixed window", key: "trusted actor plus client", windowSeconds: 60, mutation: 120, upload: 20 });
});
