import type { ChapterDocument } from "./editor-model";
const personFeature = { personFeatureId: "personfeature_aristotle", placementId: "placement_aristotle", personId: "aristotle", entityRevisionId: "revision_aristotle", name: "Aristotle", dates: "384–322 BCE", role: "Greek philosopher", teachingNote: "Character is practiced judgment.", biography: "Aristotle treats ethical formation as a practice of perceiving reasons, acting, and learning from the result.", primarySources: [], portrait: { mediaVersionId: "mediaVersion_aristotle", src: "", width: 720, height: 900, alt: "Marble bust of Aristotle", credit: "Public-domain source record", title: "Aristotle portrait", license: "Public domain" }, displayPreset: "thinker-card" as const };
export const DEMO_CHAPTER: ChapterDocument = { documentId: "chapter_ch07", chapterId: "chapter_ch07", changeSetId: "changeset_ch07_editor", slug: "aristotle-character-and-ai-assisted-life", title: "Aristotle, Character, and the AI-Assisted Life", revisionId: "revision_demo_ch07", baseRevisionId: "revision_demo_ch07", expectedVersion: 1, description: "A chapter about character and AI-assisted judgment.", chapterVersion: "7", body: [
  { type: "paragraph", blockId: "block_opening", passageId: "passage_opening", text: "An AI system can help us complete a task without helping us become the kind of person who can judge that task well." },
  { type: "heading", blockId: "block_character", sectionId: "section_character", anchorPassageId: "passage_character", level: 2, text: "Character is practiced judgment" },
  { type: "paragraph", blockId: "block_habituation", passageId: "passage_habituation", text: "For Aristotle, character is not a possession waiting inside us. It is a pattern we build through repeated choices, attention, and correction." },
  { type: "blockquote", blockId: "block_question", passageId: "passage_question", text: "What practice becomes easier when a system always decides first?" },
  { type: "paragraph", blockId: "block_practical_wisdom", passageId: "passage_practical_wisdom", text: "Practical wisdom asks what this person, in these circumstances, has reason to do. The question cannot be answered by output alone." },
], checkpoints: [{ checkpointId: "checkpoint_commit", passageId: "passage_habituation", passageExcerptHash: "a".repeat(64), displayOrder: 1, title: "Commit", trigger: "Pause after the passage.", prompt: "Name one judgment you think should remain yours when using AI.", guidance: "Use a concrete situation rather than a general principle.", stage: "Commit", strategy: "initial-judgment", responseStructure: "prose", minWords: 30, maxWords: 150, showInSidebar: true, rationale: "Makes the student's judgment visible before the later argument work." }], personFeatures: [personFeature], managedPlacements: [{ placementId: "placement_aristotle", kind: "personFeature", contentId: "personfeature_aristotle", anchorPassageId: "passage_character", position: "after", orderAtAnchor: 0, displayPreset: "thinker-card" }], people: [{ personId: "aristotle", role: "Greek philosopher", passageIds: ["passage_character"] }], entityRevisions: [{ entityRevisionId: "revision_aristotle", personId: "aristotle", sha256: "b".repeat(64), sourcePath: "content/entities/aristotle.json" }] };
