import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js';
import { z } from 'zod';

const instructions = 'Read chapters and passages first. Create or resume a changeset, make semantic edits, validate, inspect the diff, then submit. Approval and publication require a separate human release path and are not available through this MCP server. Every mutation carries the current preconditions and idempotency key. Never use raw HTML, CSS, SQL, or database patches.';
const id = z.string().min(1).max(200).regex(/^[A-Za-z0-9][A-Za-z0-9._:-]*$/);
const uuid = z.string().uuid();
const write = { changeSetId: id, baseRevisionId: id, expectedVersion: z.number().int().positive(), idempotencyKey: uuid };
const readOnly = { readOnlyHint: true, destructiveHint: false, openWorldHint: false };
const mutates = { readOnlyHint: false, destructiveHint: false, openWorldHint: false };
const position = z.union([z.object({ beforeBlockId: id }).strict(), z.object({ afterBlockId: id }).strict()]);
const checkpoint = z.object({ checkpointId: id.optional(), legacyId: z.string().min(1).max(200).optional(), passageId: id, passageExcerptHash: z.string().regex(/^[a-f0-9]{64}$/), slot: z.enum(['commit', 'work', 'reconcile']), stage: z.string().min(1).max(120), strategy: z.enum(['initial-judgment', 'self-explanation', 'argument-reconstruction', 'evidence-warrant', 'contrast-case', 'counterexample', 'consider-alternative', 'objection-repair', 'question-generation', 'epistemic-calibration', 'framework-comparison', 'transfer', 'metacognitive-trace']), title: z.string().min(1).max(200), trigger: z.string().min(1).max(300), prompt: z.string().min(1).max(4000), guidance: z.string().min(1).max(2000), responseStructure: z.enum(['prose', 'movement-plus-prose']), minWords: z.number().int().min(1).max(1000), maxWords: z.number().int().min(1).max(1000), rationale: z.string().min(1).max(2000), showInSidebar: z.boolean() }).strict().refine(v => v.minWords <= v.maxWords, 'minWords must not exceed maxWords');
const block = z.discriminatedUnion('type', [
  z.object({ type: z.literal('paragraph'), text: z.string().min(1).max(50000) }).strict(),
  z.object({ type: z.literal('heading'), text: z.string().min(1).max(1000), level: z.number().int().min(2).max(6) }).strict(),
  z.object({ type: z.literal('blockquote'), text: z.string().min(1).max(50000) }).strict(),
  z.object({ type: z.literal('callout'), text: z.string().min(1).max(20000), tone: z.enum(['note', 'warning', 'example', 'question']) }).strict(),
  z.object({ type: z.literal('list'), ordered: z.boolean(), items: z.array(z.string().min(1).max(4000)).min(1).max(100) }).strict(),
  z.object({ type: z.literal('codeBlock'), code: z.string().min(1).max(50000), language: z.string().min(1).max(50).optional() }).strict(),
  z.object({ type: z.literal('table'), rows: z.array(z.array(z.string().min(1).max(4000)).min(1).max(20)).min(1).max(100) }).strict(),
  z.object({ type: z.literal('diagram'), diagramId: id, alt: z.string().min(1).max(1000) }).strict()
]);
const fallback = z.object({ title: z.string().min(1).max(300), summary: z.string().min(1).max(4000), posterAssetId: id.optional(), transcript: z.string().min(1).max(20000).optional(), linkLabel: z.string().min(1).max(120), creator: z.string().min(1).max(300).optional(), publishedAt: z.string().datetime().optional(), accessedAt: z.string().datetime() }).strict();
const providerIdentity = z.discriminatedUnion('provider', [
  z.object({ provider: z.literal('youtube'), resourceType: z.enum(['video', 'playlist']), resourceId: z.string().min(1).max(300) }).strict(),
  z.object({ provider: z.literal('vimeo'), resourceType: z.literal('video'), resourceId: z.string().min(1).max(300), unlistedHash: z.string().min(1).max(200).optional() }).strict(),
  z.object({ provider: z.literal('x'), resourceType: z.literal('post'), resourceId: z.string().min(1).max(300) }).strict(),
  z.object({ provider: z.literal('spotify'), resourceType: z.enum(['artist', 'album', 'track', 'show', 'episode']), resourceId: z.string().min(1).max(300) }).strict(),
  z.object({ provider: z.literal('soundcloud'), resourceType: z.enum(['user', 'set', 'track']), resourceId: z.string().min(1).max(300) }).strict(),
  z.object({ provider: z.literal('bluesky'), resourceType: z.literal('post'), resourceId: z.string().min(1).max(300) }).strict()
]);
const embed = z.union([
  z.object({ kind: z.literal('externalEmbed'), embedId: id.optional(), anchorPassageId: id.optional(), identity: providerIdentity, canonicalUrl: z.string().url().startsWith('https://'), caption: z.string().min(1).max(2000), teachingUse: z.string().min(1).max(2000), displayPreset: z.enum(['compact', 'reading', 'wide']), theme: z.enum(['light', 'dark', 'auto']), fallback, adapterVersion: z.string().min(1).max(100) }).strict(),
  z.object({ kind: z.literal('richLink'), linkId: id.optional(), anchorPassageId: id.optional(), canonicalUrl: z.string().url().startsWith('https://'), title: z.string().min(1).max(300), summary: z.string().min(1).max(4000), teachingUse: z.string().min(1).max(2000), linkLabel: z.string().min(1).max(120), posterMediaVersionId: id.optional(), accessedAt: z.string().datetime() }).strict()
]);
const media = z.object({ mediaId: id, mediaVersionId: id, figureId: id.optional(), anchorPassageId: id.optional(), rightsCaseId: id, decorative: z.boolean(), alt: z.string().max(2000).optional(), caption: z.string().max(4000).optional(), captionOmissionReason: z.string().max(1000).optional(), teachingUse: z.string().min(1).max(2000), creditOverride: z.string().max(1000).optional(), displayPreset: z.enum(['narrow', 'reading', 'wide', 'bleed']), align: z.enum(['start', 'center', 'end']), animationPolicy: z.enum(['clickToPlay', 'playOnce', 'loopWithControls']).optional(), printPolicy: z.enum(['poster', 'firstFrame', 'omit']), downloadable: z.boolean() }).strict().refine(v => v.decorative || Boolean(v.alt), 'Nondecorative media requires alt text').refine(v => Boolean(v.caption || v.captionOmissionReason), 'Caption or omission reason is required').refine(v => !(v.caption && v.captionOmissionReason), 'Provide caption or captionOmissionReason, not both');
const asResult = (data) => ({ content: [{ type: 'text', text: JSON.stringify(data) }], structuredContent: data });

function api(env, requestId) {
  return async (path, method = 'GET', body) => {
    const response = await env.CONTENT_API.fetch(new Request(`https://content-api.internal${path}`, { method, headers: { accept: 'application/json', ...(body ? { 'content-type': 'application/json' } : {}), 'x-content-gateway-verified': 'v1', 'x-content-actor-id': 'actor_textbook_mcp', 'x-content-actor-type': 'agent', 'x-content-client-id': 'textbook-mcp', 'x-content-run-id': requestId, 'x-content-scopes': 'content:read content:write content:submit media:upload' }, ...(body ? { body: JSON.stringify(body) } : {}) }));
    const data = await response.json(); if (!response.ok) throw new Error(`${response.status} ${data.error?.code ?? 'CONTENT_API_ERROR'}: ${data.error?.message ?? 'Request failed'}`); return data;
  };
}
function uploadApi(env, requestId) { return async ({ ticketId, token, mimeType, sha256, bytes }) => { const response = await env.CONTENT_API.fetch(new Request(`https://content-api.internal/v1/media/uploads/${encodeURIComponent(ticketId)}`, { method: 'PUT', headers: { 'content-type': mimeType, 'content-length': String(bytes.byteLength), 'x-content-sha256': sha256, 'x-upload-token': token, 'x-content-gateway-verified': 'v1', 'x-content-actor-id': 'actor_textbook_mcp', 'x-content-actor-type': 'agent', 'x-content-client-id': 'textbook-mcp', 'x-content-run-id': requestId, 'x-content-scopes': 'media:upload' }, body: bytes })); const data = await response.json(); if (!response.ok) throw new Error(`${response.status} ${data.error?.code ?? 'UPLOAD_FAILED'}`); return data; }; }
export function createMcp(env, requestId = crypto.randomUUID()) {
  const call = api(env, requestId); const putUpload = uploadApi(env, requestId); const server = new McpServer({ name: 'ai-ethics-textbook', version: '0.1.0' }, { instructions });
  server.registerTool('list_chapters', { title: 'List Chapters', description: 'Read active canonical chapters.', outputSchema: { chapters: z.array(z.object({ id, title: z.string().optional(), current_revision_id: id.optional() }).passthrough()) }, annotations: readOnly }, async () => asResult(await call('/v1/chapters')));
  server.registerTool('get_chapter', { title: 'Get Chapter', description: 'Read one canonical chapter and its current revision.', inputSchema: { chapterId: id }, annotations: readOnly }, async ({ chapterId }) => asResult(await call(`/v1/chapters/${encodeURIComponent(chapterId)}`)));
  server.registerTool('list_passages', { title: 'List Passage Anchors', description: 'Read the first bounded page of stable passage anchors before changing anchored content.', inputSchema: { chapterId: id }, annotations: readOnly }, async ({ chapterId }) => asResult(await call(`/v1/chapters/${encodeURIComponent(chapterId)}/passages?limit=100&cursor=0`)));
  server.registerTool('get_passage_dependencies', { title: 'Get Passage Dependencies', description: 'Read checkpoint, embed, and media dependencies for one stable passage.', inputSchema: { chapterId: id, passageId: id }, annotations: readOnly }, async ({ chapterId, passageId }) => {
    const data = await call(`/v1/chapters/${encodeURIComponent(chapterId)}/dependencies?limit=100&cursor=0`);
    const edges = (data.edges ?? []).filter((edge) => edge.source === passageId || edge.target === passageId);
    const nodeIds = new Set(edges.flatMap((edge) => [edge.source, edge.target]));
    return asResult({ chapterId, passageId, revisionId: data.revisionId, nodes: (data.nodes ?? []).filter((node) => nodeIds.has(node.id)), edges, truncated: Boolean(data.page?.nextCursor) });
  });
  server.registerTool('restore_revision_as_draft', { title: 'Restore Revision as Draft', description: 'Create a new draft changeset from a prior revision; does not publish or replace canonical content.', inputSchema: { chapterId: id, revisionId: id, title: z.string().min(1).max(200), idempotencyKey: uuid }, annotations: mutates }, async ({ chapterId, revisionId, ...body }) => asResult(await call(`/v1/chapters/${encodeURIComponent(chapterId)}/revisions/${encodeURIComponent(revisionId)}:restoreAsDraft`, 'POST', body)));
  server.registerTool('create_or_resume_changeset', { title: 'Create or Resume Changeset', description: 'Open a chapter-scoped draft changeset.', inputSchema: { chapterId: id, title: z.string().min(1).max(200), description: z.string().max(2000).optional(), resume: z.boolean().optional(), idempotencyKey: uuid }, annotations: mutates }, async ({ chapterId, ...body }) => asResult(await call(`/v1/chapters/${encodeURIComponent(chapterId)}/changesets`, 'POST', body)));
  const operation = (name, title, description, schema) => server.registerTool(name, { title, description, inputSchema: { ...write, operation: schema }, annotations: mutates }, async ({ changeSetId, baseRevisionId, expectedVersion, idempotencyKey, operation }) => asResult(await call(`/v1/changesets/${encodeURIComponent(changeSetId)}:apply`, 'POST', { baseRevisionId, expectedVersion, idempotencyKey, operation })));
  operation('replace_text', 'Replace Text', 'Replace text in a named block; not raw markup.', z.object({ type: z.literal('text.replace'), blockId: id, text: z.string().min(1).max(12000) }).strict());
  operation('insert_block', 'Insert Block', 'Insert a typed content block at a stable before/after location; stable IDs are assigned by the server.', z.object({ type: z.literal('block.insert'), position, block }).strict());
  operation('move_block', 'Move Block', 'Move a block without recreating it.', z.object({ type: z.literal('block.move'), blockId: id, position }).strict());
  operation('upsert_checkpoint', 'Upsert Checkpoint', 'Create or replace an anchored reading-record checkpoint.', z.object({ type: z.enum(['checkpoint.upsert', 'checkpoint.replace']), checkpoint }).strict());
  operation('remove_checkpoint', 'Remove Checkpoint', 'Remove an immutable checkpoint slot, optionally checking its stable ID.', z.object({ type: z.literal('checkpoint.remove'), slot: z.enum(['commit', 'work', 'reconcile']), checkpointId: id.optional() }).strict());
  operation('upsert_embed', 'Upsert Embed', 'Insert or update a registered external embed or authored rich link; new blocks require a stable position.', z.object({ type: z.literal('embed.upsert'), embed, position: position.optional() }).strict());
  operation('place_media', 'Place Media', 'Place or update an approved accessible media version; new figures require a stable position.', z.object({ type: z.literal('media.place'), placement: media, position: position.optional() }).strict());
  operation('remove_media', 'Remove Media', 'Remove a placed media figure by stable figure ID.', z.object({ type: z.literal('media.remove'), figureId: id }).strict());
  const uploadRequest = { reviewPackageId: id, filename: z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/), mimeType: z.enum(['image/png','image/jpeg','image/gif','image/webp','audio/mpeg','audio/wav','audio/mp4','video/mp4','application/pdf']), bytes: z.number().int().min(1).max(25 * 1024 * 1024), sha256: z.string().regex(/^[a-f0-9]{64}$/), idempotencyKey: uuid, transcriptEquivalent: z.object({ provided: z.literal(true), language: z.string().min(1).max(40), text: z.string().min(1).max(50000) }).strict().optional(), poster: z.object({ provided: z.literal(true), alt: z.string().min(1).max(2000) }).strict().optional() };
  server.registerTool('request_media_upload', { title: 'Request Media Upload', description: 'Reserve quota and obtain a one-time upload ticket; the token is only for the following upload.', inputSchema: uploadRequest, annotations: mutates }, async (body) => asResult(await call('/v1/media:requestUpload', 'POST', body)));
  server.registerTool('create_media_review_package', { title: 'Create Pending Media Review Package', description: 'Persist structured rights, teaching-use, and accessibility declarations. The result remains pending until a human clears or blocks the exact declaration hash.', inputSchema: {
    rights: z.object({ basis: z.enum(['owned', 'licensed', 'permission', 'publicDomain', 'fairUse', 'unknown']), creator: z.string().min(1).max(300), sourceUrl: z.string().url().startsWith('https://').optional(), license: z.string().min(1).max(300).optional(), attribution: z.string().min(1).max(1000), permissionEvidenceRef: z.string().min(1).max(300).optional(), notes: z.string().min(1).max(2000).optional() }).strict(),
    editorial: z.object({ teachingUse: z.string().min(1).max(2000), placementIntent: z.string().min(1).max(1000), notes: z.string().min(1).max(2000).optional() }).strict(),
    accessibility: z.object({ decorative: z.boolean(), altText: z.string().min(1).max(1000).optional(), transcriptEquivalent: z.object({ language: z.string().min(1).max(40), text: z.string().min(1).max(50000) }).strict().optional(), motionReview: z.enum(['notApplicable', 'pending', 'passed', 'failed']).optional(), notes: z.string().min(1).max(2000).optional() }).strict(),
    idempotencyKey: uuid
  }, annotations: mutates }, async (body) => asResult(await call('/v1/media-review-packages', 'POST', body)));
  server.registerTool('search_media', { title: 'Search Media', description: 'Search ready immutable media versions for reuse, with optional rights and kind filters.', inputSchema: { query: z.string().max(100).optional(), kind: z.enum(['image', 'audio', 'video', 'document']).optional(), rightsStatus: z.enum(['reviewRequired', 'cleared', 'blocked']).optional(), sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(), limit: z.number().int().min(1).max(50).optional(), cursor: z.number().int().min(0).max(10000).optional() }, annotations: readOnly }, async ({ query, kind, rightsStatus, sha256, limit, cursor }) => {
    const params = new URLSearchParams();
    if (query) params.set('q', query); if (kind) params.set('kind', kind); if (rightsStatus) params.set('rightsStatus', rightsStatus); if (sha256) params.set('sha256', sha256); if (limit) params.set('limit', String(limit)); if (cursor !== undefined) params.set('cursor', String(cursor));
    return asResult(await call(`/v1/media${params.size ? `?${params}` : ''}`));
  });
  server.registerTool('resolve_provider_url', { title: 'Resolve Provider URL', description: 'Resolve a supported provider URL using the server-owned registry; unsupported URLs return a rich-link proposal and no network fetch occurs.', inputSchema: { url: z.string().url().startsWith('https://'), expectedProvider: z.enum(['youtube', 'vimeo', 'x', 'spotify', 'soundcloud', 'bluesky']).optional() }, annotations: readOnly }, async (body) => asResult(await call('/v1/embeds:resolve', 'POST', body)));
  server.registerTool('upload_media_base64', { title: 'Upload Media Bytes', description: 'Decode base64 and forward exact bytes to a one-time upload ticket. The token is never logged.', inputSchema: { ticketId: id, uploadToken: z.string().min(16).max(256), mimeType: uploadRequest.mimeType, sha256: uploadRequest.sha256, contentBase64: z.string().min(4).max(34_952_536) }, annotations: mutates }, async ({ ticketId, uploadToken, mimeType, sha256, contentBase64 }) => { const bytes = Uint8Array.from(atob(contentBase64), c => c.charCodeAt(0)); if (!bytes.byteLength || bytes.byteLength > 25 * 1024 * 1024) throw new Error('Decoded media exceeds the Content API limit.'); return asResult(await putUpload({ ticketId, token: uploadToken, mimeType, sha256, bytes })); });
  server.registerTool('get_media_job', { title: 'Get Media Job', description: 'Read processing state for an upload job.', inputSchema: { jobId: id }, annotations: readOnly }, async ({ jobId }) => asResult(await call(`/v1/media/jobs/${encodeURIComponent(jobId)}`)));
  server.registerTool('get_media_asset', { title: 'Get Media Asset', description: 'Read the finalized media asset and its immutable versions.', inputSchema: { mediaId: id }, annotations: readOnly }, async ({ mediaId }) => asResult(await call(`/v1/media/${encodeURIComponent(mediaId)}`)));
  server.registerTool('validate_changeset', { title: 'Validate Changeset', description: 'Validate the current draft before review.', inputSchema: { changeSetId: id }, annotations: mutates }, async ({ changeSetId }) => asResult(await call(`/v1/changesets/${encodeURIComponent(changeSetId)}:validate`, 'POST')));
  server.registerTool('diff_changeset', { title: 'Diff Changeset', description: 'Read a bounded semantic diff between canonical and working content.', inputSchema: { changeSetId: id }, annotations: readOnly }, async ({ changeSetId }) => asResult(await call(`/v1/changesets/${encodeURIComponent(changeSetId)}:diff`, 'POST')));
  server.registerTool('submit_changeset', { title: 'Submit Changeset', description: 'Freeze a validated changeset for review.', inputSchema: write, annotations: mutates }, async ({ changeSetId, baseRevisionId, expectedVersion, idempotencyKey }) => asResult(await call(`/v1/changesets/${encodeURIComponent(changeSetId)}:submitReview`, 'POST', { baseRevisionId, expectedVersion, idempotencyKey })));
  return server;
}
export default { async fetch(request, env) { if (new URL(request.url).pathname !== '/mcp') return new Response('Not found', { status: 404 }); const supplied = request.headers.get('authorization'); if (!env.MCP_ACCESS_TOKEN || supplied !== `Bearer ${env.MCP_ACCESS_TOKEN}`) return new Response('Unauthorized', { status: 401, headers: { 'www-authenticate': 'Bearer' } }); const transport = new WebStandardStreamableHTTPServerTransport({ sessionIdGenerator: undefined }); const server = createMcp(env); await server.connect(transport); return transport.handleRequest(request); } };
